import { useMemo } from "react";

export function useGoalDatePickerStyles(
  defaultDatePickerStyles: any,
  isDark: boolean,
) {
  return useMemo<any>(
    () => ({
      ...defaultDatePickerStyles,
      header: {
        ...defaultDatePickerStyles.header,
        marginBottom: 10,
        paddingTop: 0,
        paddingBottom: 0,
        paddingVertical: 0,
      },
      month_selector: {
        ...defaultDatePickerStyles.month_selector,
        backgroundColor: isDark ? "rgba(124,58,237,0.22)" : "#E9DFFF",
        borderWidth: 0,
        borderTopLeftRadius: 12,
        borderBottomLeftRadius: 12,
        borderTopRightRadius: 0,
        borderBottomRightRadius: 0,
        width: 112,
        height: 36,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
        paddingHorizontal: 0,
        paddingVertical: 0,
        marginRight: -5,
        marginLeft: -10,
      },
      year_selector: {
        ...defaultDatePickerStyles.year_selector,
        backgroundColor: isDark ? "rgba(124,58,237,0.22)" : "#E9DFFF",
        borderWidth: 0,
        borderTopLeftRadius: 0,
        borderBottomLeftRadius: 0,
        borderTopRightRadius: 12,
        borderBottomRightRadius: 12,
        marginLeft: 5,
        marginRight: -5,
        width: 112,
        height: 36,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
        paddingHorizontal: 0,
        paddingVertical: 0,
      },
      month_selector_label: {
        ...defaultDatePickerStyles.month_selector_label,
        color: isDark ? "#F5F3FF" : "#3B0764",
        fontWeight: "800",
        fontSize: 16,
        lineHeight: 20,
        textAlign: "center",
        textAlignVertical: "center",
        includeFontPadding: false,
        paddingVertical: 0,
        width: "100%",
      },
      year_selector_label: {
        ...defaultDatePickerStyles.year_selector_label,
        color: isDark ? "#F5F3FF" : "#3B0764",
        fontWeight: "800",
        fontSize: 16,
        lineHeight: 20,
        textAlign: "center",
        textAlignVertical: "center",
        includeFontPadding: false,
        paddingVertical: 0,
        width: "100%",
      },
      month: {
        ...defaultDatePickerStyles.month,
        backgroundColor: isDark ? "rgba(124,58,237,0.08)" : "#F5F3FF",
        borderColor: isDark ? "rgba(196,181,253,0.24)" : "#DDD6FE",
        borderWidth: 1,
      },
      month_label: {
        ...defaultDatePickerStyles.month_label,
        color: isDark ? "#F5F3FF" : "#1F2937",
        fontWeight: "700",
      },
      selected_month: {
        ...defaultDatePickerStyles.selected_month,
        backgroundColor: "#7C3AED",
        borderColor: "#7C3AED",
      },
      selected_month_label: {
        ...defaultDatePickerStyles.selected_month_label,
        color: "#FFFFFF",
        fontWeight: "800",
      },
      year: {
        ...defaultDatePickerStyles.year,
        backgroundColor: isDark ? "rgba(124,58,237,0.08)" : "#F5F3FF",
        borderColor: isDark ? "rgba(196,181,253,0.24)" : "#DDD6FE",
        borderWidth: 1,
      },
      year_label: {
        ...defaultDatePickerStyles.year_label,
        color: isDark ? "#F5F3FF" : "#1F2937",
        fontWeight: "700",
      },
      selected_year: {
        ...defaultDatePickerStyles.selected_year,
        backgroundColor: "#7C3AED",
        borderColor: "#7C3AED",
      },
      selected_year_label: {
        ...defaultDatePickerStyles.selected_year_label,
        color: "#FFFFFF",
        fontWeight: "800",
      },
      active_year: {
        ...defaultDatePickerStyles.active_year,
        backgroundColor: isDark ? "rgba(124,58,237,0.18)" : "#E9DFFF",
        borderColor: isDark ? "rgba(196,181,253,0.45)" : "#A78BFA",
      },
      active_year_label: {
        ...defaultDatePickerStyles.active_year_label,
        color: isDark ? "#F5F3FF" : "#3B0764",
        fontWeight: "800",
      },
      button_prev: {
        ...defaultDatePickerStyles.button_prev,
        backgroundColor: isDark ? "rgba(124,58,237,0.28)" : "#7C3AED",
        borderColor: isDark ? "rgba(196,181,253,0.55)" : "#6D28D9",
        borderWidth: 1,
        width: 34,
        height: 34,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
      },
      button_next: {
        ...defaultDatePickerStyles.button_next,
        backgroundColor: isDark ? "rgba(124,58,237,0.28)" : "#7C3AED",
        borderColor: isDark ? "rgba(196,181,253,0.55)" : "#6D28D9",
        borderWidth: 1,
        width: 34,
        height: 34,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
      },
      button_prev_image: {
        ...defaultDatePickerStyles.button_prev_image,
        tintColor: "#FFFFFF",
        alignSelf: "center",
      },
      button_next_image: {
        ...defaultDatePickerStyles.button_next_image,
        tintColor: "#FFFFFF",
        alignSelf: "center",
      },
      weekday_label: {
        ...defaultDatePickerStyles.weekday_label,
        color: isDark ? "rgba(237,233,254,0.82)" : "#6D28D9",
        fontWeight: "600",
      },
      day: {
        ...defaultDatePickerStyles.day,
        borderRadius: 10,
      },
      day_label: {
        ...defaultDatePickerStyles.day_label,
        color: isDark ? "#F5F3FF" : "#1F2937",
        fontWeight: "600",
      },
      selected: {
        ...defaultDatePickerStyles.selected,
        backgroundColor: "#7C3AED",
        borderRadius: 10,
      },
      selected_label: {
        ...defaultDatePickerStyles.selected_label,
        color: "#FFFFFF",
        fontWeight: "800",
      },
      today: {
        ...defaultDatePickerStyles.today,
        borderColor: "#8B5CF6",
        borderWidth: 1.5,
      },
      outside_label: {
        ...defaultDatePickerStyles.outside_label,
        color: isDark ? "rgba(245,243,255,0.3)" : "rgba(31,41,55,0.35)",
      },
      disabled_label: {
        ...defaultDatePickerStyles.disabled_label,
        color: isDark ? "rgba(245,243,255,0.28)" : "rgba(31,41,55,0.28)",
      },
    }),
    [defaultDatePickerStyles, isDark],
  );

}

