import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    borderRadius: 16,
    marginHorizontal: 16,
    marginVertical: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    overflow: "hidden",
  },
  cardGradient: {
    padding: 16,
    borderRadius: 16,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    flex: 1,
    minWidth: 0,
    marginRight: 10,
  },
  actions: {
    flexDirection: "row",
    gap: 12,
    zIndex: 5,
  },
  iconButton: {
    padding: 4,
  },
  content: {
    gap: 12,
  },
  amountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  amountBlock: {
    flex: 1,
    minWidth: 0,
  },
  remainingBlock: {
    flexShrink: 1,
    minWidth: 0,
    alignItems: "flex-end",
  },
  amount: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    maxWidth: "100%",
  },
  remaining: {
    fontSize: 14,
    color: "#EDE9FE",
    textAlign: "right",
    maxWidth: 150,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  date: {
    fontSize: 12,
    color: "#EDE9FE",
  },
  target: {
    fontSize: 12,
    color: "#EDE9FE",
  },
  reachedBadge: {
    marginTop: 0,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(16,185,129,0.18)",
    borderColor: "rgba(16,185,129,0.45)",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  reachedText: {
    color: "#D1FAE5",
    fontSize: 12,
    fontWeight: "700",
  },
  inProgressBadge: {
    marginTop: 0,
    marginBottom: 10,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(245,158,11,0.18)",
    borderColor: "rgba(245,158,11,0.45)",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inProgressText: {
    color: "#FEF3C7",
    fontSize: 12,
    fontWeight: "700",
  },
  button: {
    marginTop: 16,
  },
  decorCircleTop: {
    position: "absolute",
    top: -46,
    right: -42,
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  decorCircleBottom: {
    position: "absolute",
    bottom: -50,
    left: -48,
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
});

