import { StyleSheet } from "react-native";

import { Fonts } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: "center",
    gap: 10,
  },
  loadingTitle: {
    fontFamily: Fonts.sansBold,
    fontSize: 18,
    textAlign: "center",
  },
  loadingSubtitle: {
    fontFamily: Fonts.sansMedium,
    fontSize: 14,
    textAlign: "center",
  },
  header: { paddingHorizontal: 20, paddingBottom: 12 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerRowRtl: { flexDirection: "row-reverse" },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontFamily: Fonts.sansBlack, fontSize: 22 },
  avatarBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  pressed: { opacity: 0.7, transform: [{ scale: 0.96 }] },
  disabled: { opacity: 0.5 },
  searchWrap: { paddingHorizontal: 20, marginBottom: 12 },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingRight: 8,
    gap: 12,
    backgroundColor: "rgba(232,222,248,0.4)",
  },
  searchInput: {
    flex: 1,
    fontFamily: Fonts.sansMedium,
    fontSize: 16,
    height: "100%",
  },
  filterBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#6200EE",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  cloudContent: { paddingHorizontal: 16, paddingTop: 8 },
  cloudGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  cloudGridRtl: { flexDirection: "row-reverse" },
  emptyBox: { minHeight: 240, alignItems: "center", justifyContent: "center" },
  emptyText: { fontFamily: Fonts.sansMedium, fontSize: 15 },
  bubbleWrap: { marginBottom: 6 },
  bubble: {
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 9999,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  bubbleIdle: { backgroundColor: "rgba(232,222,248,0.6)" },
  bubbleActive: {
    backgroundColor: "#6200EE",
    shadowColor: "#6200EE",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  bubbleLabel: { fontFamily: Fonts.sansBold, fontSize: 15, lineHeight: 20 },
  bubbleLabelActive: { color: "#FFFFFF" },
  bubbleLabelIdle: { color: "#6200EE" },
  rtlText: { textAlign: "right" },
  bottomArea: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
  },
  bottomGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    top: -90,
    bottom: 0,
  },
  customInputRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 14,
    backgroundColor: "rgba(232,222,248,0.5)",
    shadowColor: "#6200EE",
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  customInput: {
    flex: 1,
    fontFamily: Fonts.sansMedium,
    fontSize: 16,
    height: "100%",
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.05)",
  },
  ctaWrap: {
    width: "100%",
    borderRadius: 18,
    shadowColor: "#6200EE",
    shadowOpacity: 0.4,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
});


